from .maven import MavenAPI
import json

response = MavenAPI.search("rxandroid")
# response = MavenAPI.gid("io.reactivex.rxjava2")
if response.encoding:
    decoded_content = response.content.decode(response.encoding)
else:
    decoded_content = response.content.decode("utf-8")

json_response = json.loads(decoded_content)
array_results = json_response["response"]["docs"]

for result in array_results:
    # ArtifactId
    # This element indicates the unique base name of the primary artifact being generated by this project. The primary
    # artifact for a project is typically a JAR file. Secondary artifacts like source bundles also use the artifactId
    # as part of their final name. A typical artifact produced by Maven would have the form
    # <artifactId>-<version>.<extension>
    # print(result["a"])

    # GroupId
    # This element indicates the unique identifier of the organization or group that created the project. The groupId
    # is one of the key identifiers of a project and is typically based on the fully qualified domain name of your
    # organization. For example org.apache.maven.plugins is the designated groupId for all Maven plugins.
    # print(result["g"])
    # print(result["id"])

    print("implementation group: '{group_id}', name: '{artifact_id}', version: '{version}'"
          .format(group_id=result["g"],
                  artifact_id=result["a"],
                  version=result["latestVersion"]))

    print()
